---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: aozora
# description will be included in the image's metadata
description: Custom Fedora Atomic based OS image

base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: 41

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - installrpmfusion.sh
      - installproprietarypackages.sh

  - type: rpm-ostree
    install:
      - heif-pixbuf-loader
      - ffmpeg
      - ffmpeg-libs
      - ffmpegthumbnailer
      - pipewire-libs-extra
      - libfdk-aac
      - gstreamer1-plugins-bad
      - gstreamer1-plugins-ugly 
    remove:
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-bad-free-libs
      - gstreamer1-plugins-ugly-free
      - fdk-aac-free
      - ffmpeg-free
      - libavcodec-free  
      - libavdevice-free
      - libavfilter-free
      - libavformat-free  
      - libavutil-free  
      - libpostproc-free  
      - libswresample-free  
      - libswscale-free  

  - type: rpm-ostree
    install:
      # Desktop enviroment
      - sddm
      - sddm-themes
      - hyprland
      - waybar
      - xdg-desktop-portal-hyprland
      - hyprpaper
      - hyprlock
      - hypridle
      - pavucontrol
      - xdg-user-dirs
      - xfce-polkit
      - xorg-x11-server-Xwayland
      - kwallet
      - pam-kwallet

      # screenshot
      - slurp
      - grim

      # display
      - wlr-randr
      - wlsunset
      - brightnessctl
      - ddccontrol

      # notifications
      - dunst

      # theme and GUI
      - fontawesome-fonts-all

      # networking
      - network-manager-applet
      - blueman

      # sound
      - pipewire
      - wireplumber

      # file manager
      - thunar
      - thunar-archive-plugin
      - thunar-volman
      - xarchiver
      - imv
      - p7zip
      - gvfs-mtp
      - gvfs-gphoto2
      - gvfs-smb
      - gvfs-nfs
      - gvfs-fuse
      - gvfs-archive
      - android-tools

      # development
      - git
      - distrobox
      - neovim

    remove:
      - firefox
      - firefox-langpacks
      - toolbox

  - type: systemd
    system:
      enabled:
        - sddm-boot.service

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.mozilla.firefox
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

